user:
  test: 123567
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou_springcloud?useUnicode=true&characterEncoding=utf8
    username: root
    password: swx12345@
